id: P004177
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W9752
  title: བློ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    2de814686edd4e4a80039157eb79f758:
      image_group_id: I6113
      title: ''
      volume_number: 1
      total_pages: 470
      base_file: v001.txt
