id: P004177
initial_creation_type: ocr
source_metadata:
  id: bdr:W9752
  title: བློ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    2de814686edd4e4a80039157eb79f758:
      image_group_id: I6113
      title: ''
      volume_number: 1
      total_pages: 470
